name: Validate Feed

on:
  pull_request:
    branches:
      - '**'
    paths:
      - 'public/feed.rss'

# This doesn't yet do automatic validation, but will prompt
# those that updated the feed to not forget to validate it.

jobs:
  validate-feed:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Looks like you made a change to the RSS feed. Please validate your change against https://podba.se/validate/ and https://validator.w3.org/feed/, thanks!'
            })
